### ISSUE TITLE
How do you tell grunt-scss-lint to ignore a particular line in a .scss file?

### ISSUE THREAD

**Issue by JudithHuang** [ahmednuaman/grunt-scss-lint#149]
```scss
textarea.form-control { // scss-lint:disable QualifyingElement
    padding: 10px;
  }
```
