### ISSUE TITLE
scss-lint exiting before showing files with errors

### ISSUE THREAD

**Issue by kemiga** [ahmednuaman/grunt-scss-lint#35]
When I run grunt scsslint, I get five files output into the console, all "lint free", but then scss-lint exits (with error code 65) before showing any files which contain errors. Any suggestions about what I might be missing/doing wrong, or how I can get a complete list of the files that failed?

```
gruntfile.js

scsslint {
  options: {
        config: '.scss-lint.yml'
    },
    files: {
        src: [
            '<%= paths.src %>/scss/**/*.scss',
            '!<%= paths.src %>/scss/vendor/**/*.scss'
        ]
    }
}


.scss-lint.yml

# SCSS Lint config
# Originally from https://github.com/causes/scss-lint/blob/master/config/default.yml

linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: false

  HexFormat:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  Indentation:
    enabled: true
    width: 4

  LeadingZero:
    enabled: true
    style: include_zero # or 'exclude_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern

  PlaceholderInExtend:
    enabled: true

  PropertySortOrder:
    enabled: true

  PropertySpelling:
    enabled: true
    extra_properties: []

  SelectorDepth:
    enabled: true
    max_depth: 4

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: false

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false

```
